spring:
  cloud:
    config:
      discovery:
        serviceId: configserver
        enabled: true
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 20
        multiplier: 3
      server:
        git:
          uri: https://github.com/spourdas/SpringConfig

